on:
  webhook:
    method: .*post
jobs:
  email:
  name: Post a email to plutotom
  runs-on: ubuntu-latest
  steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.zoho.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: ${{ on }}
        # Literal body:
        body: ${{ on.body }}
        # Read file contents as body:
        to: plutotom@live.com
        from: plutotom@Live.com # <user@example.com>
        # Optional content type (defaults to text/plain):
        content_type: text/html
